"""
The dictionary is meant for mapping Reuters classification of companies sectors into the Bloomberg ones, used in
FinancialNewsSemanticScraper ontology for companies classes.
Names corresponds to Reuters class and values corresponds to the Bloomberg one
eg:
 Commodity Chemicals :    Materials
    -- Reuters --      -- Bloomberg --
"""

br_classes = {
    # Materials
    'Commodity Chemicals': 'Materials',
    'Agricultural Chemicals': 'Materials',
    'Specialty Chemicals': 'Materials',
    'Diversified Chemicals': 'Materials',
    'Precious metals & Minerals': 'Materials',
    'Steel': 'Materials',
    'Aluminum': 'Materials',
    'Specialty Mining & Metals': 'Materials',
    'Gold': 'Materials',
    'Mining Support Services & Equipment': 'Materials',
    'Integrated Mining': 'Materials',
    'Construction Materials': 'Materials',
    'Forest & Wood Products': 'Materials',
    'Paper Products': 'Materials',
    'Non-Paper Containers & Packaging': 'Materials',
    'Paper Packaging': 'Materials',
    # Energy
    'Coal': 'Energy',
    'Integrated Oil and gas': 'Energy',
    'Oil & Gas Exploration and Production': 'Energy',
    'Oil & Gas Refining and Marketing': 'Energy',
    'Oil & Gas Drilling': 'Energy',
    'Oil-related Services and Equipment': 'Energy',
    'Oil & Gas Transportation Services': 'Energy',
    'Renewable Energy Equipment & Services': 'Energy',
    'Renewable Fuels': 'Energy',
    'Uranium': 'Energy',
    # Health Care
    'Advanced Medical Equipment': 'Health Care',
    'Medical Equipment, Supplies & Distribution': 'Health Care',
    'Healthcare Facilities & Services': 'Health Care',
    'Managed Healthcare': 'Health Care',
    'Diversified Pharmaceuticals': 'Health Care',
    'Generic & Specialty Pharmaceuticals': 'Health Care',
    'Pharmaceuticals': 'Health Care',
    'Biotechnology & Medical Research': 'Health Care',
    # Communication Services
    'Integrated Telecommunications Services': 'Communication Services',
    'Wireless Telecommunications Services': 'Communication Services',
    'Advertising & Marketing': 'Communication Services',
    'Broadcasting': 'Communication Services',
    'Entertainment Production': 'Communication Services',
    'Consumer Publishing': 'Communication Services',
    'Diversified Media': 'Communication Services',
    # Consumer Staples
    'Brewers': 'Consumer Staples',
    'Distillers & Wineries': 'Consumer Staples',
    'Non-Alcoholic Beverages': 'Consumer Staples',
    'Fishing & Farming': 'Consumer Staples',
    'Food Processing': 'Consumer Staples',
    'Tobacco': 'Consumer Staples',
    'Household Products': 'Consumer Staples',
    'Personal Products': 'Consumer Staples',
    'Personal Services': 'Consumer Staples',
    'Drug Retailers': 'Consumer Staples',
    'Food Distribution & Convenience Stores': 'Consumer Staples',
    # Utilities
    'Electric Utilities': 'Utilities',
    'Independent Power Producers': 'Utilities',
    'Natural Gas Utilities': 'Utilities',
    'Water & Other Utilities': 'Utilities',
    'Multiline Utilities': 'Utilities',
    # Financials
    'Banks': 'Financials',
    'Consumer Financial Services': 'Financials',
    'Corporate Financial Services': 'Financials',
    'Investment Banking & Brokerage Services': 'Financials',
    'Investment Management & Fund Operators': 'Financials',
    'Diversified Investment Services': 'Financials',
    'Specialty Investment Services': 'Financials',
    'Financial & Commodity Market Operators': 'Financials',
    'Diversified Financial Services': 'Financials',
    'Multiline Insurance': 'Financials',
    'Property & Casualty Insurance': 'Financials',
    'Life & Health Insurance': 'Financials',
    'Reinsurance': 'Financials',
    'Insurance Brokers': 'Financials',
    'Investment Trusts': 'Financials',
    'Mutual Funds': 'Financials',
    'Closed End Funds': 'Financials',
    'Exchange Traded Funds': 'Financials',
    'Pension Funds': 'Financials',
    'Insurance Funds': 'Financials',
    'Holding Companies': 'Financials',
    # Information Technology
    'Semiconductors': 'Information Technology',
    'Semiconductor Equipment & Testing': 'Information Technology',
    'Communications Equipment': 'Information Technology',
    'Electronic Equipments & Parts': 'Information Technology',
    'Office Equipment': 'Information Technology',
    'Computer Hardware': 'Information Technology',
    'Phones & Handheld Devices': 'Information Technology',
    'Household Electronics': 'Information Technology',
    'IT Services & Consulting': 'Information Technology',
    'Software': 'Information Technology',
    'Internet Services': 'Information Technology',
    # Industrials
    'Aerospace & Defense': 'Industrials',
    'Industrial Machinery & Equipment': 'Industrials',
    'Heavy Machinery & Vehicles': 'Industrials',
    'Electrical Components & Equipment': 'Industrials',
    'Heavy Electrical Equipment': 'Industrials',
    'Shipbuilding': 'Industrials',
    'Construction & Engineering': 'Industrials',
    'Diversified Trading & Distributing': 'Industrials',
    'Environmental Services & Equipment': 'Industrials',
    'Commercial Printing Services': 'Industrials',
    'Employment Services': 'Industrials',
    'Business Support Services': 'Industrials',
    'Business Support Supplies': 'Industrials',
    'Professional Information Services': 'Industrials',
    'Industrial Conglomerates': 'Industrials',
    'Air Freight & Courier Services': 'Industrials',
    'Marine Freight & Logistics': 'Industrials',
    'Ground Freight & Logistics': 'Industrials',
    'Airlines': 'Industrials',
    'Passenger Transportation, Ground & Sea': 'Industrials',
    'Airport Services': 'Industrials',
    'Marine Port Services': 'Industrials',
    'Highways & Rail Tracks': 'Industrials',
    # Real Estate
    'Real Estate Development & Operations': 'Real Estate',
    'Real Estate Services': 'Real Estate',
    'Diversified REITs': 'Real Estate',
    'Commercial REITs': 'Real Estate',
    'Residential REITs': 'Real Estate',
    'Specialized REITs': 'Real Estate',
    # Consumer Discretionary
    'Auto & Truck Manufacturers': 'Consumer Discretionary',
    'Auto, Truck & Motorcycle Parts': 'Consumer Discretionary',
    'Tires & Rubber Products': 'Consumer Discretionary',
    'Textiles & Leather Goods': 'Consumer Discretionary',
    'Apparel & Accessories': 'Consumer Discretionary',
    'Footwear': 'Consumer Discretionary',
    'Homebuilding': 'Consumer Discretionary',
    'Construction Supplies & Fittings': 'Consumer Discretionary',
    'Consumer Electronics': 'Consumer Discretionary',
    'Appliances, Tools & Housewares': 'Consumer Discretionary',
    'Home Furnishing': 'Consumer Discretionary',
    'Toys & Juvenile Products': 'Consumer Discretionary',
    'Recreational Products': 'Consumer Discretionary',
    'Hotels, Motels & Cruise Lines': 'Consumer Discretionary',
    'Restaurants & Bars': 'Consumer Discretionary',
    'Casinos & Gaming': 'Consumer Discretionary',
    'Leisure & Recreation': 'Consumer Discretionary',
    'Department Stores': 'Consumer Discretionary',
    'Discount Stores': 'Consumer Discretionary',
    'Auto Vehicles, Parts & Service Retailers': 'Consumer Discretionary',
    'Home Improvement Products & Services Retailers': 'Consumer Discretionary',
    'Home Furnishings Retailers': 'Consumer Discretionary',
    'Apparel & Accessories Retailers': 'Consumer Discretionary',
    'Computer & Electronics Retailers': 'Consumer Discretionary',
    'Miscellaneous Specialty Retailers': 'Consumer Discretionary',

    # Oth from Reuters
    'Advertising': 'Communication Services',
    'Air Courier': 'Industrials',
    'Airline': 'Industrials',
    'Apparel/Accessories': 'Consumer Discretionary',
    'Appliance & Tool': 'Consumer Discretionary',
    'Audio & Video Equipment': 'Consumer Discretionary',
    'Auto & Truck Parts': 'Consumer Discretionary',
    'Basic Materials': 'Materials',
    'Beverages (Alcoholic)': 'Consumer Staples',
    'Beverages (Nonalcoholic)': 'Consumer Staples',
    'Biotechnology & Drugs': 'Health Care',
    'Broadcasting & Cable TV': 'Communication Services',
    'Business Services': 'Industrials',
    'Capital Goods': 'Financials',
    'Chemical Manufacturing': 'Consumer Discretionary',
    'Chemicals - Plastics & Rubber': 'Materials',
    'Communications Services': 'Communication Services',
    'Computer Networks': 'Information Technology',
    'Computer Peripherals': 'Information Technology',
    'Computer Services': 'Communication Services',
    'Conglomerates': 'Industrials',
    'Constr. Supplies & Fittings': 'Consumer Discretionary',
    'Constr. & Agric. Machinery': 'Industrials',
    'Construction - Raw Materials': 'Materials',
    'Construction Services': 'Industrials',
    'Consumer Cyclical': 'Consumer Staples',
    'Consumer/Non-Cyclical': 'Consumer Discretionary',
    'Containers & Packaging': 'Materials',
    'Crops': 'Consumer Staples',
    'Electronic Instr. & Controls': 'Information Technology',
    'Energy': 'Energy',
    'Fabricated Plastic & Rubber': 'Consumer Discretionary',
    'Financial': 'Financials',
    'Fish/Livestock': 'Consumer Staples',
    'Forestry & Wood Products': 'Materials',
    'Furniture & Fixtures': 'Consumer Discretionary',
    'Gold & Silver': 'Materials',
    'Healthcare': 'Health Care',
    'Healthcare Facilities': 'Health Care',
    'Hotels & Motels': 'Consumer Discretionary',
    'Insurance (Life)': 'Financials',
    'Insurance (Miscellaneous)': 'Financials',
    'Insurance (Prop. & Casualty)': 'Financials',
    'Investment Services': 'Financials',
    'Iron & Steel': 'Materials',
    'Major Drugs': 'Health Care',
    'Medical Equipment & Supplies': 'Health Care',
    'Metal Mining': 'Materials',
    'Misc. Capital Goods': 'Financials',
    'Misc. Fabricated Products': 'Consumer Discretionary',
    'Misc. Financial Services': 'Financials',
    'Misc. Transportation': 'Industrials',
    'Motion Pictures': 'Communication Services',
    'Non-Metallic Mining': 'Materials',
    'Office Supplies': 'Consumer Discretionary',
    'Oil & Gas - Integrated': 'Energy',
    'Oil & Gas Operations': 'Energy',
    'Oil Well Services & Equipment': 'Energy',
    'Personal & Household Prods': 'Consumer Staples',
    'Photography': 'Communication Services',
    'Printing & Publishing': 'Communication Services',
    'Printing Services': 'Communication Services',
    'Railroads': 'Industrials',
    'Real Estate Operations': 'Real Estate',
    'Recreational Activities': 'Consumer Discretionary',
    'Regional Banks': 'Financials',
    'Rental & Leasing': 'Consumer Discretionary',
    'Restaurants': 'Consumer Discretionary',
    'Retail (Apparel)': 'Consumer Discretionary',
    'Retail (Catalog & Mail Order)': 'Consumer Discretionary',
    'Retail (Department & Discount)': 'Consumer Discretionary',
    'Retail (Grocery)': 'Consumer Discretionary',
    'Retail (Home Improvement)': 'Consumer Discretionary',
    'Retail (Specialty)': 'Consumer Discretionary',
    'Retail (Technology)': 'Consumer Discretionary',
    'Schools': 'Consumer Staples',
    'Scientific & Technical Instr.': 'Consumer Staples',
    'Security Systems & Services': 'Consumer Discretionary',
    'Services': 'Consumer Discretionary',
    'Software & Programming': 'Information Technology',
    'Technology': 'Industrials',
    'Textiles - Non Apparel': 'Consumer Discretionary',
    'Tires': 'Consumer Discretionary',
    'Transportation': 'Industrials',
    'Trucking': 'Consumer Discretionary',
    'Utilities': 'Utilities',
    'Waste Management Services': 'Utilities',
    'Water Transportation': 'Materials',
    'Water Utilities': 'Utilities',
}


def remove_whitespaces(s: str) -> str:
    return s.replace(" ", "")


# if __name__ == "__main__":
#    print(remove_whitespaces(br_classes['Computer Services']))
